meta-mingles/metamingle-server

src/main/java/com/mingles/metamingle/member/query/application/dto/request/FindMemberRequest.java
src/main/java/com/mingles/metamingle/member/query/application/dto/response/MemberQueryResponse.java
src/main/java/com/mingles/metamingle/member/query/application/dto/temp.java
src/main/java/com/mingles/metamingle/member/query/application/service/MemberQueryService.java
src/main/java/com/mingles/metamingle/member/query/application/service/temp.java
src/main/java/com/mingles/metamingle/member/query/infrastructure/repository/MemberQueryRepository.java
src/main/java/com/mingles/metamingle/member/query/infrastructure/repository/temp.java

* closed #19 
- @numerical43 확인 부탁드립니당~!

Feature/member [Member] query domain - service, repository 생성

---

src/main/java/com/mingles/metamingle/interativemovie/query/domain/repository/InteractiveMovieQueryRepository.java
src/main/java/com/mingles/metamingle/shortform/command/application/dto/request/DeleteShortFormRequest.java
src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/CreateShortFormResponse.java
src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/DeleteShortFormResponse.java
src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormListResponse.java
src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormResponse.java
src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/InteractiveMovieDTO.java
src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiInteractiveMovieService.java

- closed #24
- ShortFrom 상세 조회
- IsInteractiveMovie가 true : 연관된 InteractiveMovie들의 no, choice, url을 함께 반환
- IsInteractiveMovie가 false : null 반환

feature : #24 shortForm 조회 시 interactiveMovie 정보 함께 반환

---

src/main/java/com/mingles/metamingle/interativemovie/command/application/dto/response/CreateInteractiveMovieResponse.java
src/main/java/com/mingles/metamingle/interativemovie/command/application/service/InteractiveMovieCommandService.java
src/main/java/com/mingles/metamingle/interativemovie/query/application/dto/response/GetInteractiveMovieResponse.java
src/main/resources/db.data/data.sql

- closed #26 
- interactiveMovie의 response, request의 접근 제어자 수정
- interactiveCommandService에서 interactiveMovie를 저장할 때 1L을 쓰도록 수정 (임시값)
- interactiveMovie와 shortForm 테스트를 위해 data.sql 추가

Feature/interactive [InteractiveMovie] response, request, data.sql, 임시 memberNo 설정

---

src/main/java/com/mingles/metamingle/script/command/application/controller/ScriptCommandController.java
src/main/java/com/mingles/metamingle/script/command/application/dto/request/CreateScriptRequest.java
src/main/java/com/mingles/metamingle/script/command/application/dto/request/UpdateScriptRequest.java
src/main/java/com/mingles/metamingle/script/command/application/dto/response/ScriptCommandResponse.java
src/main/java/com/mingles/metamingle/script/command/application/dto/response/ScriptInfraResponse.java
src/main/java/com/mingles/metamingle/script/command/application/service/ScriptCommandService.java
src/main/java/com/mingles/metamingle/script/command/domain/aggregate/entity/Script.java
src/main/java/com/mingles/metamingle/script/command/infrastructure/service/ScriptCommandInfraService.java
src/main/java/com/mingles/metamingle/script/query/application/dto/request/FindScriptRequest.java
src/main/java/com/mingles/metamingle/script/query/application/dto/response/ScriptQueryResponse.java
src/main/java/com/mingles/metamingle/script/query/application/dto/temp.java
src/main/java/com/mingles/metamingle/script/query/application/service/ScriptQueryService.java
src/main/java/com/mingles/metamingle/script/query/application/service/temp.java
src/main/java/com/mingles/metamingle/script/query/infrastructure/repository/ScriptQueryRepository.java
src/main/java/com/mingles/metamingle/script/query/infrastructure/repository/temp.java

* closed #31 
- 대본 재생성을 위해 테이블에 memberContent (회원이 대본생성을 위해 입력한 글) 칼럼 추가했습니다.

Feature/script [Script] AI 통신 후 수정 & Update 로직 추가

---

src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
src/main/java/com/mingles/metamingle/shortform/query/domain/repository/ShortFormQueryRepository.java

* closed #35
- ShortForm 전체 조회 시 오래된 순 조회에서 최신순 조회로 변경

feature : #35 shortForm 전체 조회 정렬 변경

---

src/main/java/com/mingles/metamingle/script/query/application/controller/ScriptQueryController.java
src/main/java/com/mingles/metamingle/script/query/application/controller/temp.java
src/main/resources/db/data/data.sql

Feature/script 대본 Command 서비스, 컨트롤러

---

src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java

- closed #43 
- 인터랙티브 무비 통신 방법 수정
- shortForm과 같은 form-data 형식으로 받는 방법으로 수정

refactoring : #43 인터랙티브 무비 통신 방법 수정

---

src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
src/main/java/com/mingles/metamingle/shortform/query/domain/repository/ShortFormQueryRepository.java

- closed #35
숏폼 전체 조회 시 정렬이 등록순이었던 것을 최신순으로 변경

feature : #35 숏폼 전체 조회 정렬 변경 (최신순)

---

src/main/java/com/mingles/metamingle/movielike/command/application/controller/InteractiveMovieLIkeCommandController.java
src/main/java/com/mingles/metamingle/movielike/command/application/controller/temp.java
src/main/java/com/mingles/metamingle/movielike/command/application/dto/requeset/temp.java
src/main/java/com/mingles/metamingle/movielike/command/application/dto/response/CreateInteractiveMovieLikeResponse.java
src/main/java/com/mingles/metamingle/movielike/command/application/dto/temp.java
src/main/java/com/mingles/metamingle/movielike/command/application/service/InteractiveMovieLikeCommandService.java
src/main/java/com/mingles/metamingle/movielike/command/application/service/temp.java
src/main/java/com/mingles/metamingle/movielike/command/domain/aggregate/entity/InteractiveMovieLike.java
src/main/java/com/mingles/metamingle/movielike/command/domain/aggregate/entity/temp.java
src/main/java/com/mingles/metamingle/movielike/command/domain/aggregate/vo/InteractiveMovieLikeVO.java
src/main/java/com/mingles/metamingle/movielike/command/domain/aggregate/vo/temp.java
src/main/java/com/mingles/metamingle/movielike/command/domain/repository/InteractiveMovieLikeCommandRepository.java
src/main/java/com/mingles/metamingle/movielike/command/domain/repository/temp.java
src/main/java/com/mingles/metamingle/movielike/query/application/controller/InteractiveMovieLikeQueryController.java
src/main/java/com/mingles/metamingle/movielike/query/application/controller/temp.java
src/main/java/com/mingles/metamingle/movielike/query/application/dto/request/temp.java
src/main/java/com/mingles/metamingle/movielike/query/application/dto/response/CountInteractiveMovieLike.java
src/main/java/com/mingles/metamingle/movielike/query/application/dto/response/GetInteractiveMovieLike.java
src/main/java/com/mingles/metamingle/movielike/query/application/dto/temp.java
src/main/java/com/mingles/metamingle/movielike/query/application/service/InteractiveMovieLikeQueryService.java
src/main/java/com/mingles/metamingle/movielike/query/application/service/temp.java
src/main/java/com/mingles/metamingle/movielike/query/domain/repository/InteractiveMovieLikeQueryRepository.java
src/main/java/com/mingles/metamingle/movielike/query/domain/service/temp.java

- closed #50 
- InteractiveMovieLike 저장
- InteractiveMovieLike 조회
- InteractiveMovieLike 삭제

Feature/interactivelike : InteractiveMovieLike 기능

---

src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java

- closed #57
- 인터랙티브 무비 저장 오류 수정
- 숏폼 조회 시 url 대신 thumbnail url이 조회되는 오류 수정

feature : #57 인터랙티브 무비 저장, 숏폼 조회 오류

---

src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormListResponse.java
src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java

- closed #59
- 숏폼 전체 조회 시, 인터랙티브 무비인 경우 관련된 인터랙티브 무비의 정보까지 함께 조회하도록 기능 수정

feature : #59 숏폼 전체 조회 데이터 변경

---

src/main/resources/db/data/data.sql

- closed #60
- data.sql로 넣는 더미 데이터 변경
- 직접 찍은 동영상을 아바타 모션 캡쳐 동영상으로 변경

Feature/shortform : data.sql 더미 데이터 변경

---

src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormListResponse.java
src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormResponse.java
src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/ShortFormLikeInfoDTO.java
src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiShortFormLikeQueryService.java

- closed #63 
- shortForm List 조회, shortForm 상세 조회 시 shortForm의 좋아요 수 & 내가 좋아요했는지 여부를 함께 조회

feature : #63 shortForm List & 상세 조회 시 좋아요 수 & 좋아요 여부 조회

---

src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
src/main/java/com/mingles/metamingle/interactivemovie/command/infrastructure/service/ApiShortFormService.java
src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
src/main/java/com/mingles/metamingle/shortform/command/application/service/ShortFormFirebaseService.java
src/main/java/com/mingles/metamingle/shortform/query/application/controller/ShortFormQueryController.java

- closed #80 
- 헤더에 있는 토큰으로 사용자를 구별하도록 수정

Feature/shortform : 헤더에 있는 토큰으로 사용자를 구별하도록 수정

---

src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java

- closed #82
- 토큰으로 사용자 구별하도록 수정

feature : #82 토큰으로 사용자 구별하도록 수정

---

src/main/java/com/mingles/metamingle/shortformlike/command/application/controller/ShortFormLikeCommandController.java
src/main/java/com/mingles/metamingle/shortformlike/query/application/controller/ShortFormLikeQueryController.java

- closed #83
- 헤더에 있는 토큰으로 사용자를 구별하도록 수정

feature : #83 토큰으로 사용자 구별하도록 수정

---

src/main/java/com/mingles/metamingle/movielike/command/application/controller/InteractiveMovieLIkeCommandController.java
src/main/java/com/mingles/metamingle/movielike/query/application/controller/InteractiveMovieLikeQueryController.java

- closed #84
- 헤더의 토큰으로 사용자 구별하도록 수정

feature : #84 토큰으로 사용자 구별하도록 수정

---

src/main/java/com/mingles/metamingle/configuration/MongoDBConfig.java
src/main/java/com/mingles/metamingle/creativetool/document/Image.java
src/main/java/com/mingles/metamingle/creativetool/document/Sound.java
src/main/java/com/mingles/metamingle/creativetool/query/application/controller/CreativeToolController.java
src/main/java/com/mingles/metamingle/creativetool/query/application/dto/request/ImageRequest.java
src/main/java/com/mingles/metamingle/creativetool/query/application/dto/request/SoundRequest.java
src/main/java/com/mingles/metamingle/creativetool/query/application/dto/response/ImageResponse.java
src/main/java/com/mingles/metamingle/creativetool/query/application/dto/response/SoundResponse.java
src/main/java/com/mingles/metamingle/creativetool/query/application/service/CreativeToolService.java
src/main/java/com/mingles/metamingle/creativetool/query/domain/mongo/ImageRepository.java
src/main/java/com/mingles/metamingle/creativetool/query/domain/mongo/SoundRepository.java
src/main/java/com/mingles/metamingle/scenario/command/application/controller/ScenarioCommandController.java
src/main/java/com/mingles/metamingle/scenario/command/application/dto/request/SaveScenarioRequest.java
src/main/java/com/mingles/metamingle/scenario/command/application/service/ScenarioCommandService.java
src/main/java/com/mingles/metamingle/scenario/command/domain/aggregate/document/Scenario.java
src/main/java/com/mingles/metamingle/scenario/command/domain/mongo/ScenarioCommandRepository.java
src/main/java/com/mingles/metamingle/scenario/command/infrastructure/service/ScenarioCommandInfraService.java
src/test/java/com/mingles/metamingle/command/application/service/ScenarioCommandServiceTests.java

* closed #88 
- AI로 생성된 이미지/BGM 을 mongoDB 저장
- 저장된 데이터들을 필요에 따라 조회
- 이미지의 경우 임시로 5개 랜덤 조회
- json 파일로 MongoDB addData 해주세용요용

Feature/mongodb: Creative Tool 이용시 필요한 이미지, 사운드 데이터 조회

---

src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
src/main/java/com/mingles/metamingle/shortform/command/application/service/ShortFormFirebaseService.java

- 숏폼 생성의 ReqeustHeader 임시 삭제
- 인터랙티브 무비의 RequestHeader 임시 삭제

Feature/shortform : 영상 생성 기능의 RequestHeader 임시 삭제

---

src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
src/main/resources/db/data/data.sql

- closed #94
- 인터랙티브 무비를 저장할 때 첫번째 영상, 첫번째 영상, 두번째 영상으로 저장되는 오류 수정 -> 첫번째 영상, 두번째 영상, 세번째 영상으로 제대로 저장되도록 수정

feature : #94 인터랙티브 무비 저장 오류 수정

---

src/main/java/com/mingles/metamingle/avatar/command/application/controller/AvatarCommandController.java
src/main/java/com/mingles/metamingle/avatar/command/application/controller/temp.java
src/main/java/com/mingles/metamingle/avatar/command/application/dto/request/AvatarCommandRequest.java
src/main/java/com/mingles/metamingle/avatar/command/application/dto/request/temp.java
src/main/java/com/mingles/metamingle/avatar/command/application/dto/response/AvatarCommandResponse.java
src/main/java/com/mingles/metamingle/avatar/command/application/dto/response/temp.java
src/main/java/com/mingles/metamingle/avatar/command/application/dto/temp.java
src/main/java/com/mingles/metamingle/avatar/command/application/service/AvatarCommandService.java
src/main/java/com/mingles/metamingle/avatar/command/application/service/temp.java
src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/entity/Avatar.java
src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/entity/temp.java
src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/vo/AvatarMemberNoVO.java
src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/vo/temp.java
src/main/java/com/mingles/metamingle/avatar/command/domain/repository/AvatarCommandRepository.java
src/main/java/com/mingles/metamingle/avatar/command/domain/repository/temp.java
src/main/java/com/mingles/metamingle/avatar/query/application/controller/AvatarQueryController.java
src/main/java/com/mingles/metamingle/avatar/query/application/controller/temp.java
src/main/java/com/mingles/metamingle/avatar/query/application/dto/response/AvatarQueryResponse.java
src/main/java/com/mingles/metamingle/avatar/query/application/dto/temp.java
src/main/java/com/mingles/metamingle/avatar/query/application/service/AvatarQueryService.java
src/main/java/com/mingles/metamingle/avatar/query/application/service/temp.java
src/main/java/com/mingles/metamingle/avatar/query/infrastructure/repository/AvatarQueryRepository.java
src/main/java/com/mingles/metamingle/avatar/query/infrastructure/repository/temp.java

* closed #53 
* closed #107 
* closed #108 
- 아바타 통신 관련 논의해봐야 할 것 같습니다
- 아직 최종본 아닙니당

Feature/avatar - 엔티티 수정 및 조회/저장/수정 로직 구현

---

src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
src/main/java/com/mingles/metamingle/interactivemovie/query/application/controller/InteractiveMovieQueryController.java
src/main/java/com/mingles/metamingle/movielike/command/application/controller/InteractiveMovieLIkeCommandController.java
src/main/java/com/mingles/metamingle/movielike/query/application/controller/InteractiveMovieLikeQueryController.java

- closed #117
- 컨트롤러에 @RequestHeader로 토큰을 무조건 받도록 수정

feature : #117 interactive 관련 컨트롤러에 requestHeaader 추가
